### ISSUE TITLE
Provide a mechanism for performing annotation queries in a scene

### ISSUE THREAD

**Issue by dprokop** [grafana/scenes#313]
```[tasklist]
### Tasks
- [x] [Provide infrastructure for executing annotation queries and merging them to panel data](https://github.com/grafana/scenes/pull/325)
- [x] [Implement `AnnotationsDataLayer` that is responsible for querying and processing annotations](https://github.com/grafana/scenes/pull/328)
- [x] [Provide API to filter annotations by panelId](https://github.com/grafana/scenes/pull/329)
- [x] [Allow toggling individual layer on/off](https://github.com/grafana/scenes/pull/333)
- [x] [Support individual layer cancellation](https://github.com/grafana/scenes/pull/337)
- [x] Handle annotation queries errors
- [x] [Add support for template variables](https://github.com/grafana/scenes/pull/358)
- [x] [Deduplicate annotations](https://github.com/grafana/scenes/pull/351)
- [x] Cancel annotation queries on time range change
- [x] Support legacy annotations runner
- [ ] ~Handle annotation config and mappings without the transient AnnotationEvents model~
```
