### ISSUE TITLE
ScenesReact: Epic follow-up issues & tasks

### ISSUE THREAD

**Issue by torkelo** [grafana/scenes#761]
Epic with followup tasks following the merging of https://github.com/grafana/scenes/pull/734

**Fundamentals**
* [ ] Basic design doc outlining the basic working of the approach 
* [ ] Url sync for objects added and removed from scene graph after initial sync 
* [ ] Url sync for same scene across page routes 
* [ ] Transformations
* [ ] Annotations & data layers
* [ ] Migration / interoperability (Had to remove support for contexts inside EmbeddedScene when I moved everything to a separate repo) 

**Caching**
* [ ] Caching of data state 
* [ ] Caching of viz panel state 
* [ ] Caching of query variable state (that is not above page routes) 

**Components**
* [ ] CustomVariable + test
* [ ] QueryVariable + test
* [ ] DataSourceVariable + test
* [ ] LocalValueVariable 
* [ ] AdHocFiltersVariable 
* [ ] GroupByVariable 

**Components** nice to have
* [ ] CSSGridVizLayout (not critical but helps for standard / common viz layouts & default responsive views)
* [ ] FlexVizLayout (not critical but helps for standard / common viz layouts & default responsive views)

**Hooks** 
* [ ] useVariableValues should have tests and be generic 
* [ ] useVariableValue hook + test
* [ ] useVariableQuery (if your not interested in using a variable as a variable but only the resulting value options) 
* [ ] useDataTransformer

**Docs**'
* [ ] Intro to `@grafana/scenes`
* [ ] Variable docs
* [ ] Visualization docs 
* [ ] Using custom scene objects
* [ ] Migration

**Comment by torkelo** [comment]
@axelavargas I removed the assignments, I think it should be clear that anyone can pick up tasks from this epic, just add your name to the task before (and maybe write about it in #wg-scenes
